
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.p1.ed.ReglasGram.Users;

import com.mycompany.p1.ed.Nodos.NodeAVL;
import com.mycompany.p1.ed.arboles.AVL;
import com.mycompany.p1.ed.objetos.*;
import com.mycompany.p1.ed.listas.*;
import com.mycompany.p1.ed.ReglasGram.Token;
import java_cup.runtime.*;
import com.mycompany.p1.ed.ReglasGram.Users.symUser.*;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserUser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return symUser.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserUser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserUser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserUser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\016\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\002\003\000\002\003\005\000\002\004\003" +
    "\000\002\004\003\000\002\005\004\000\002\005\003\000" +
    "\002\006\005\000\002\006\003\000\002\006\004\000\002" +
    "\007\003\000\002\007\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\025\000\010\003\007\004\006\010\004\001\002\000" +
    "\004\005\ufffb\001\002\000\004\005\014\001\002\000\004" +
    "\005\ufffc\001\002\000\010\002\ufffe\004\ufffe\010\ufffe\001" +
    "\002\000\010\002\013\004\006\010\004\001\002\000\010" +
    "\002\uffff\004\uffff\010\uffff\001\002\000\010\002\000\004" +
    "\000\010\000\001\002\000\004\002\001\001\002\000\012" +
    "\003\020\004\016\007\022\010\015\001\002\000\006\006" +
    "\ufff4\007\ufff4\001\002\000\006\006\ufff5\007\ufff5\001\002" +
    "\000\006\006\025\007\026\001\002\000\004\006\024\001" +
    "\002\000\006\006\ufff7\007\ufff7\001\002\000\010\002\ufff9" +
    "\004\ufff9\010\ufff9\001\002\000\010\002\ufffd\004\ufffd\010" +
    "\ufffd\001\002\000\006\006\ufff6\007\ufff6\001\002\000\006" +
    "\004\016\010\015\001\002\000\010\002\ufffa\004\ufffa\010" +
    "\ufffa\001\002\000\006\006\ufff8\007\ufff8\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\025\000\010\002\007\003\010\004\004\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\003\011\004\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\005\022" +
    "\006\016\007\020\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\007\026\001\001\000\002\001\001\000\002\001\001" +
    "" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserUser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserUser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserUser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




	private List<String> listaErrores;
	private AVL TreeUser;
	private ListCircular listaImagenes;
	private ListSimple lista;
	private Usuario user; 

	public ParserUser(LexerUser lex, ListCircular listaImagenes){
		super(lex);
		listaErrores = new ArrayList<String>();
		TreeUser = new AVL();
		this.listaImagenes = listaImagenes;
		lista = new ListSimple();
		user = new Usuario();
	}
	public void syntax_error(Symbol cur_token){
			String nombreSimbolo = symbl_name_from_id(cur_token.sym);
            Token token = (Token) cur_token.value;
			String msgError =  "Error: ( "+ token.getLexema() +" ) -> {Linea: "+cur_token.left+", Columna: "+ cur_token.right +" }" ;
			listaErrores.add(msgError);
	}

	public void report_fatal_error(String message, Object info){
			String Elerror = "Error Irrecuperable: " + message + " -> {objeto: " + info + "}";
			listaErrores.add(Elerror);	
	}

	public List getListaErrores(){
		return listaErrores;
	}
	public AVL getListUsers(){
		return TreeUser;
	}

	protected int error_sync_size(){
		return 1;
	}
	private void insertarUsuarios(){
		try{
			user.setImagenes(lista);
			TreeUser.add(user.getId(),user);
		}catch(Exception e){
			//System.out.println("error al insertar el usuario: " + e.getMessage());
		}
		user = new Usuario();
		lista =  new ListSimple();
	}
	private void verificarImg(Token TokenImg){
		String idImg = TokenImg.getLexema();
		if(listaImagenes != null){
			Imagen img =  listaImagenes.buscar(idImg);
			if(img != null){
				lista.add(idImg);
			}else{
				System.out.println("no esta la imagen: " + idImg);
			}
		}else{
			System.out.println("No hay ninguna imagen cargada");
		}
		
	}




/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserUser$actions {
  private final ParserUser parser;

  /** Constructor */
  CUP$ParserUser$actions(ParserUser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserUser$do_action_part00000000(
    int                        CUP$ParserUser$act_num,
    java_cup.runtime.lr_parser CUP$ParserUser$parser,
    java.util.Stack            CUP$ParserUser$stack,
    int                        CUP$ParserUser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserUser$result;

      /* select the action based on the action number */
      switch (CUP$ParserUser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= usuarios EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserUser$stack.elementAt(CUP$ParserUser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserUser$stack.elementAt(CUP$ParserUser$top-1)).right;
		Token start_val = (Token)((java_cup.runtime.Symbol) CUP$ParserUser$stack.elementAt(CUP$ParserUser$top-1)).value;
		RESULT = start_val;
              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.elementAt(CUP$ParserUser$top-1)), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserUser$parser.done_parsing();
          return CUP$ParserUser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // usuarios ::= usuarios usuario 
            {
              Token RESULT =null;

              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("usuarios",0, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.elementAt(CUP$ParserUser$top-1)), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          return CUP$ParserUser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // usuarios ::= usuario 
            {
              Token RESULT =null;

              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("usuarios",0, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          return CUP$ParserUser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // usuarios ::= error 
            {
              Token RESULT =null;

              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("usuarios",0, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          return CUP$ParserUser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // usuario ::= idUser DOS_PUNTOS usuario_sig 
            {
              Token RESULT =null;
		insertarUsuarios();
              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("usuario",1, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.elementAt(CUP$ParserUser$top-2)), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          return CUP$ParserUser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // idUser ::= STRING 
            {
              Token RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()).right;
		Token s = (Token)((java_cup.runtime.Symbol) CUP$ParserUser$stack.peek()).value;
		user.setId(s.getLexema());
              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("idUser",2, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          return CUP$ParserUser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // idUser ::= NUMERO 
            {
              Token RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()).right;
		Token n = (Token)((java_cup.runtime.Symbol) CUP$ParserUser$stack.peek()).value;
		user.setId(n.getLexema());
              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("idUser",2, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          return CUP$ParserUser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // usuario_sig ::= imagenes SEMI 
            {
              Token RESULT =null;

              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("usuario_sig",3, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.elementAt(CUP$ParserUser$top-1)), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          return CUP$ParserUser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // usuario_sig ::= SEMI 
            {
              Token RESULT =null;

              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("usuario_sig",3, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          return CUP$ParserUser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // imagenes ::= imagenes COMA imagen 
            {
              Token RESULT =null;

              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("imagenes",4, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.elementAt(CUP$ParserUser$top-2)), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          return CUP$ParserUser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // imagenes ::= imagen 
            {
              Token RESULT =null;

              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("imagenes",4, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          return CUP$ParserUser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // imagenes ::= error COMA 
            {
              Token RESULT =null;

              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("imagenes",4, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.elementAt(CUP$ParserUser$top-1)), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          return CUP$ParserUser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // imagen ::= STRING 
            {
              Token RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()).right;
		Token s = (Token)((java_cup.runtime.Symbol) CUP$ParserUser$stack.peek()).value;
		verificarImg(s);
              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("imagen",5, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          return CUP$ParserUser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // imagen ::= NUMERO 
            {
              Token RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()).right;
		Token n = (Token)((java_cup.runtime.Symbol) CUP$ParserUser$stack.peek()).value;
		verificarImg(n);
              CUP$ParserUser$result = parser.getSymbolFactory().newSymbol("imagen",5, ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserUser$stack.peek()), RESULT);
            }
          return CUP$ParserUser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserUser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserUser$do_action(
    int                        CUP$ParserUser$act_num,
    java_cup.runtime.lr_parser CUP$ParserUser$parser,
    java.util.Stack            CUP$ParserUser$stack,
    int                        CUP$ParserUser$top)
    throws java.lang.Exception
    {
              return CUP$ParserUser$do_action_part00000000(
                               CUP$ParserUser$act_num,
                               CUP$ParserUser$parser,
                               CUP$ParserUser$stack,
                               CUP$ParserUser$top);
    }
}

}
