
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.p1.ed.ReglasGram.capas;

import com.mycompany.p1.ed.Matrices.MatrizDispersa;
import com.mycompany.p1.ed.arboles.AVL;
import com.mycompany.p1.ed.objetos.Capa;
import com.mycompany.p1.ed.ReglasGram.Token;
import java_cup.runtime.*;
import com.mycompany.p1.ed.ReglasGram.capas.symCapas.*;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserCapas extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return symCapas.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserCapas() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserCapas(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserCapas(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\015\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\002\003\000\002\003\005\000\002\005\004" +
    "\000\002\005\003\000\002\004\003\000\002\004\003\000" +
    "\002\006\004\000\002\006\003\000\002\007\010\000\002" +
    "\007\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\030\000\010\003\007\004\005\007\004\001\002\000" +
    "\004\005\ufff9\001\002\000\004\005\ufffa\001\002\000\010" +
    "\002\uffff\004\uffff\007\uffff\001\002\000\010\002\ufffe\004" +
    "\ufffe\007\ufffe\001\002\000\010\002\032\004\005\007\004" +
    "\001\002\000\004\005\012\001\002\000\010\003\015\006" +
    "\014\007\013\001\002\000\004\010\024\001\002\000\010" +
    "\002\ufffb\004\ufffb\007\ufffb\001\002\000\004\010\023\001" +
    "\002\000\010\002\ufffd\004\ufffd\007\ufffd\001\002\000\010" +
    "\003\015\006\021\007\013\001\002\000\010\003\ufff7\006" +
    "\ufff7\007\ufff7\001\002\000\010\002\ufffc\004\ufffc\007\ufffc" +
    "\001\002\000\010\003\ufff8\006\ufff8\007\ufff8\001\002\000" +
    "\010\003\ufff5\006\ufff5\007\ufff5\001\002\000\004\007\025" +
    "\001\002\000\004\010\026\001\002\000\004\004\027\001" +
    "\002\000\004\011\030\001\002\000\010\003\ufff6\006\ufff6" +
    "\007\ufff6\001\002\000\010\002\000\004\000\007\000\001" +
    "\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\030\000\010\002\007\003\005\004\010\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\003\030\004\010\001\001\000\002\001" +
    "\001\000\010\005\015\006\016\007\017\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\007\021\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserCapas$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserCapas$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserCapas$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




	private List<String> listaErrores;
	private AVL treeCapas;
	private Capa onlyCap;
	private MatrizDispersa MD;

	public ParserCapas(LexerCapas lex){
		super(lex);
		listaErrores = new ArrayList<String>();
		treeCapas = new AVL();
		onlyCap = new Capa();
		MD = new MatrizDispersa();
	}
	public void syntax_error(Symbol cur_token){
			String nombreSimbolo = symbl_name_from_id(cur_token.sym);
            Token token = (Token) cur_token.value;
			String msgError =  "Error: ( "+ token.getLexema() +" ) -> {Linea: "+cur_token.left+", Columna: "+ cur_token.right +" }" ;
			listaErrores.add(msgError);
	}

	public void report_fatal_error(String message, Object info){
			String Elerror = "Error Irrecuperable: " + message + " -> {objeto: " + info + "}";
			listaErrores.add(Elerror);	
	}

	public List getListaErrores(){
		return listaErrores;
	}
	public AVL getTreeCapas(){
		return treeCapas;
	}

	protected int error_sync_size(){
		return 1;
	}
	private void insertarCapaTree(){
		try{
			onlyCap.setMatriz(MD);
			treeCapas.add(onlyCap.getId(), onlyCap);
			//onlyCap = new Capa();
			//MD = new MatrizDispersa();
		}catch(Exception e){
			//System.out.println("error al insertar capa: " + e.getMessage());
		}
		onlyCap = new Capa();
		MD = new MatrizDispersa();

	}




/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserCapas$actions {
  private final ParserCapas parser;

  /** Constructor */
  CUP$ParserCapas$actions(ParserCapas parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserCapas$do_action_part00000000(
    int                        CUP$ParserCapas$act_num,
    java_cup.runtime.lr_parser CUP$ParserCapas$parser,
    java.util.Stack            CUP$ParserCapas$stack,
    int                        CUP$ParserCapas$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserCapas$result;

      /* select the action based on the action number */
      switch (CUP$ParserCapas$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= capas EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)).right;
		Token start_val = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)).value;
		RESULT = start_val;
              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserCapas$parser.done_parsing();
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // capas ::= capas capa 
            {
              Token RESULT =null;

              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("capas",0, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // capas ::= capa 
            {
              Token RESULT =null;

              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("capas",0, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // capas ::= error 
            {
              Token RESULT =null;

              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("capas",0, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // capa ::= id LLAI capa_sig 
            {
              Token RESULT =null;
		insertarCapaTree();
              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("capa",1, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-2)), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // capa_sig ::= parametros LLAD 
            {
              Token RESULT =null;

              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("capa_sig",3, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // capa_sig ::= LLAD 
            {
              Token RESULT =null;

              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("capa_sig",3, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // id ::= STRING 
            {
              Token RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()).right;
		Token s = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.peek()).value;
		onlyCap.setId(s.getLexema());
              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("id",2, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // id ::= NUMERO 
            {
              Token RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()).right;
		Token n = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.peek()).value;
		onlyCap.setId(n.getLexema());
              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("id",2, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // parametros ::= parametros parametro 
            {
              Token RESULT =null;

              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("parametros",4, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // parametros ::= parametro 
            {
              Token RESULT =null;

              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("parametros",4, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // parametro ::= NUMERO COMA NUMERO COMA STRING SEMI 
            {
              Token RESULT =null;
		int filaleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-5)).left;
		int filaright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-5)).right;
		Token fila = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-5)).value;
		int colleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-3)).left;
		int colright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-3)).right;
		Token col = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)).right;
		Token c = (Token)((java_cup.runtime.Symbol) CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)).value;
		
						try{
							MD.insertar(Integer.parseInt(col.getLexema()),Integer.parseInt(fila.getLexema()),c.getLexema());
						}catch(Exception e){
							System.out.println("Error al ingresar un nuevo nodoMatriz: " + e.getMessage());
						}						
						
              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("parametro",5, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-5)), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // parametro ::= error COMA 
            {
              Token RESULT =null;

              CUP$ParserCapas$result = parser.getSymbolFactory().newSymbol("parametro",5, ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.elementAt(CUP$ParserCapas$top-1)), ((java_cup.runtime.Symbol)CUP$ParserCapas$stack.peek()), RESULT);
            }
          return CUP$ParserCapas$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserCapas$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserCapas$do_action(
    int                        CUP$ParserCapas$act_num,
    java_cup.runtime.lr_parser CUP$ParserCapas$parser,
    java.util.Stack            CUP$ParserCapas$stack,
    int                        CUP$ParserCapas$top)
    throws java.lang.Exception
    {
              return CUP$ParserCapas$do_action_part00000000(
                               CUP$ParserCapas$act_num,
                               CUP$ParserCapas$parser,
                               CUP$ParserCapas$stack,
                               CUP$ParserCapas$top);
    }
}

}
