
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.p1.ed.ReglasGram.capas;

/** CUP generated class containing symbol constants. */
public class symCapas {
  /* terminals */
  public static final int COMA = 6;
  public static final int NUMERO = 5;
  public static final int LLAD = 4;
  public static final int STRING = 2;
  public static final int error = 1;
  public static final int SEMI = 7;
  public static final int LLAI = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRING",
  "LLAI",
  "LLAD",
  "NUMERO",
  "COMA",
  "SEMI"
  };
}

